/**
*
* @file hilsim_ipcore_hw.h
*
* This header file contains identifiers and driver functions (or
* macros) that can be used to access the device.  The user should refer to the
* hardware device specification for more details of the device operation.
*/ 
#define HILSIM_IPCORE_SYSTEM_RUN 0x10/**< system_run */
#define HILSIM_IPCORE_SLICE2_XD_PRESC_SHIFT 0x1b0/**< slice2_xd_presc_shift */
#define HILSIM_IPCORE_SLICE2_XD_PRESC_MUL 0x1b4/**< slice2_xd_presc_mul */
#define HILSIM_IPCORE_SLICE2_XD_NLF_PRESC 0x198/**< slice2_xd_nlf_presc */
#define HILSIM_IPCORE_SLICE2_XD_NLF_GAIN 0x19c/**< slice2_xd_nlf_gain */
#define HILSIM_IPCORE_SLICE2_XD_MUX 0x190/**< slice2_xd_mux */
#define HILSIM_IPCORE_SLICE2_XD_GAIN 0x194/**< slice2_xd_gain */
#define HILSIM_IPCORE_SLICE2_X_PRESC_SHIFT 0x1b8/**< slice2_x_presc_shift */
#define HILSIM_IPCORE_SLICE2_X_PRESC_MUL 0x1bc/**< slice2_x_presc_mul */
#define HILSIM_IPCORE_SLICE2_X_NLF_PRESC 0x188/**< slice2_x_nlf_presc */
#define HILSIM_IPCORE_SLICE2_X_NLF_GAIN 0x18c/**< slice2_x_nlf_gain */
#define HILSIM_IPCORE_SLICE2_X_MUX 0x180/**< slice2_x_mux */
#define HILSIM_IPCORE_SLICE2_X_GAIN 0x184/**< slice2_x_gain */
#define HILSIM_IPCORE_SLICE2_U_NLF_PRESC 0x1a8/**< slice2_u_nlf_presc */
#define HILSIM_IPCORE_SLICE2_U_NLF_GAIN 0x1ac/**< slice2_u_nlf_gain */
#define HILSIM_IPCORE_SLICE2_U_MUX 0x1a0/**< slice2_u_mux */
#define HILSIM_IPCORE_SLICE2_U_GAIN 0x1a4/**< slice2_u_gain */
#define HILSIM_IPCORE_SLICE1_XD_PRESC_SHIFT 0x170/**< slice1_xd_presc_shift */
#define HILSIM_IPCORE_SLICE1_XD_PRESC_MUL 0x174/**< slice1_xd_presc_mul */
#define HILSIM_IPCORE_SLICE1_XD_NLF_PRESC 0x158/**< slice1_xd_nlf_presc */
#define HILSIM_IPCORE_SLICE1_XD_NLF_GAIN 0x15c/**< slice1_xd_nlf_gain */
#define HILSIM_IPCORE_SLICE1_XD_MUX 0x150/**< slice1_xd_mux */
#define HILSIM_IPCORE_SLICE1_XD_GAIN 0x154/**< slice1_xd_gain */
#define HILSIM_IPCORE_SLICE1_X_PRESC_SHIFT 0x178/**< slice1_x_presc_shift */
#define HILSIM_IPCORE_SLICE1_X_PRESC_MUL 0x17c/**< slice1_x_presc_mul */
#define HILSIM_IPCORE_SLICE1_X_NLF_PRESC 0x148/**< slice1_x_nlf_presc */
#define HILSIM_IPCORE_SLICE1_X_NLF_GAIN 0x14c/**< slice1_x_nlf_gain */
#define HILSIM_IPCORE_SLICE1_X_MUX 0x140/**< slice1_x_mux */
#define HILSIM_IPCORE_SLICE1_X_GAIN 0x144/**< slice1_x_gain */
#define HILSIM_IPCORE_SLICE1_U_NLF_PRESC 0x168/**< slice1_u_nlf_presc */
#define HILSIM_IPCORE_SLICE1_U_NLF_GAIN 0x16c/**< slice1_u_nlf_gain */
#define HILSIM_IPCORE_SLICE1_U_MUX 0x160/**< slice1_u_mux */
#define HILSIM_IPCORE_SLICE1_U_GAIN 0x164/**< slice1_u_gain */
#define HILSIM_IPCORE_SLICE0_XD_PRESC_SHIFT 0x130/**< slice0_xd_presc_shift */
#define HILSIM_IPCORE_SLICE0_XD_PRESC_MUL 0x134/**< slice0_xd_presc_mul */
#define HILSIM_IPCORE_SLICE0_XD_NLF_PRESC 0x118/**< slice0_xd_nlf_presc */
#define HILSIM_IPCORE_SLICE0_XD_NLF_GAIN 0x11c/**< slice0_xd_nlf_gain */
#define HILSIM_IPCORE_SLICE0_XD_MUX 0x110/**< slice0_xd_mux */
#define HILSIM_IPCORE_SLICE0_XD_GAIN 0x114/**< slice0_xd_gain */
#define HILSIM_IPCORE_SLICE0_X_PRESC_SHIFT 0x138/**< slice0_x_presc_shift */
#define HILSIM_IPCORE_SLICE0_X_PRESC_MUL 0x13c/**< slice0_x_presc_mul */
#define HILSIM_IPCORE_SLICE0_X_NLF_PRESC 0x108/**< slice0_x_nlf_presc */
#define HILSIM_IPCORE_SLICE0_X_NLF_GAIN 0x10c/**< slice0_x_nlf_gain */
#define HILSIM_IPCORE_SLICE0_X_MUX 0x100/**< slice0_x_mux */
#define HILSIM_IPCORE_SLICE0_X_GAIN 0x104/**< slice0_x_gain */
#define HILSIM_IPCORE_SLICE0_U_NLF_PRESC 0x128/**< slice0_u_nlf_presc */
#define HILSIM_IPCORE_SLICE0_U_NLF_GAIN 0x12c/**< slice0_u_nlf_gain */
#define HILSIM_IPCORE_SLICE0_U_MUX 0x120/**< slice0_u_mux */
#define HILSIM_IPCORE_SLICE0_U_GAIN 0x124/**< slice0_u_gain */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC1_XX2_PRESC 0xf0/**< out_mat_nlf_dac1_xx2_presc */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC1_XX2_GAIN 0xf4/**< out_mat_nlf_dac1_xx2_gain */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC1_XX2_EN 0xec/**< out_mat_nlf_dac1_xx2_en */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC1_XX1_PRESC 0xe4/**< out_mat_nlf_dac1_xx1_presc */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC1_XX1_GAIN 0xe8/**< out_mat_nlf_dac1_xx1_gain */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC1_XX1_EN 0xe0/**< out_mat_nlf_dac1_xx1_en */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC1_XX0_PRESC 0xd8/**< out_mat_nlf_dac1_xx0_presc */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC1_XX0_GAIN 0xdc/**< out_mat_nlf_dac1_xx0_gain */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC1_XX0_EN 0xd4/**< out_mat_nlf_dac1_xx0_en */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC0_XX2_PRESC 0xcc/**< out_mat_nlf_dac0_xx2_presc */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC0_XX2_GAIN 0xd0/**< out_mat_nlf_dac0_xx2_gain */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC0_XX2_EN 0xc8/**< out_mat_nlf_dac0_xx2_en */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC0_XX1_PRESC 0xc0/**< out_mat_nlf_dac0_xx1_presc */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC0_XX1_GAIN 0xc4/**< out_mat_nlf_dac0_xx1_gain */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC0_XX1_EN 0xbc/**< out_mat_nlf_dac0_xx1_en */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC0_XX0_PRESC 0xb4/**< out_mat_nlf_dac0_xx0_presc */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC0_XX0_GAIN 0xb8/**< out_mat_nlf_dac0_xx0_gain */
#define HILSIM_IPCORE_OUT_MAT_NLF_DAC0_XX0_EN 0xb0/**< out_mat_nlf_dac0_xx0_en */
#define HILSIM_IPCORE_OUT_MAT_FAC_DAC1_XX2 0xac/**< out_mat_fac_dac1_xx2 */
#define HILSIM_IPCORE_OUT_MAT_FAC_DAC1_XX1 0xa8/**< out_mat_fac_dac1_xx1 */
#define HILSIM_IPCORE_OUT_MAT_FAC_DAC1_XX0 0xa4/**< out_mat_fac_dac1_xx0 */
#define HILSIM_IPCORE_OUT_MAT_FAC_DAC0_XX2 0x94/**< out_mat_fac_dac0_xx2 */
#define HILSIM_IPCORE_OUT_MAT_FAC_DAC0_XX1 0x90/**< out_mat_fac_dac0_xx1 */
#define HILSIM_IPCORE_OUT_MAT_FAC_DAC0_XX0 0x8c/**< out_mat_fac_dac0_xx0 */
#define HILSIM_IPCORE_OUT_MAT_DAC1_SELX2 0xa0/**< out_mat_dac1_selx2 */
#define HILSIM_IPCORE_OUT_MAT_DAC1_SELX1 0x9c/**< out_mat_dac1_selx1 */
#define HILSIM_IPCORE_OUT_MAT_DAC1_SELX0 0x98/**< out_mat_dac1_selx0 */
#define HILSIM_IPCORE_OUT_MAT_DAC0_SELX2 0x88/**< out_mat_dac0_selx2 */
#define HILSIM_IPCORE_OUT_MAT_DAC0_SELX1 0x84/**< out_mat_dac0_selx1 */
#define HILSIM_IPCORE_OUT_MAT_DAC0_SELX0 0x80/**< out_mat_dac0_selx0 */
#define HILSIM_IPCORE_LED_VALUE 0x0/**< led_value */
#define HILSIM_IPCORE_INP_MAT_FAC_U2_NOISE 0x60/**< inp_mat_fac_u2_noise */
#define HILSIM_IPCORE_INP_MAT_FAC_U2_ADC1 0x5c/**< inp_mat_fac_u2_adc1 */
#define HILSIM_IPCORE_INP_MAT_FAC_U2_ADC0 0x58/**< inp_mat_fac_u2_adc0 */
#define HILSIM_IPCORE_INP_MAT_FAC_U1_NOISE 0x54/**< inp_mat_fac_u1_noise */
#define HILSIM_IPCORE_INP_MAT_FAC_U1_ADC1 0x50/**< inp_mat_fac_u1_adc1 */
#define HILSIM_IPCORE_INP_MAT_FAC_U1_ADC0 0x4c/**< inp_mat_fac_u1_adc0 */
#define HILSIM_IPCORE_INP_MAT_FAC_U0_NOISE 0x48/**< inp_mat_fac_u0_noise */
#define HILSIM_IPCORE_INP_MAT_FAC_U0_ADC1 0x44/**< inp_mat_fac_u0_adc1 */
#define HILSIM_IPCORE_INP_MAT_FAC_U0_ADC0 0x40/**< inp_mat_fac_u0_adc0 */
#define HILSIM_IPCORE_CFG_SYSTEM_RESET 0x38/**< cfg_system_reset */
#define HILSIM_IPCORE_CFG_NOISE_PRESC2 0x34/**< cfg_noise_presc2 */
#define HILSIM_IPCORE_CFG_NOISE_PRESC1 0x30/**< cfg_noise_presc1 */
#define HILSIM_IPCORE_CFG_NOISE_PRESC0 0x2c/**< cfg_noise_presc0 */
#define HILSIM_IPCORE_CFG_NLF_WE 0x1c/**< cfg_nlf_we */
#define HILSIM_IPCORE_CFG_NLF_START 0x14/**< cfg_nlf_start */
#define HILSIM_IPCORE_CFG_NLF_SELECT 0x20/**< cfg_nlf_select */
#define HILSIM_IPCORE_CFG_NLF_DATA 0x28/**< cfg_nlf_data */
#define HILSIM_IPCORE_CFG_NLF_ADDR 0x24/**< cfg_nlf_addr */
#define HILSIM_IPCORE_ADC1_NLF_PRESC 0x1cc/**< adc1_nlf_presc */
#define HILSIM_IPCORE_ADC1_NLF_GAIN 0x1d0/**< adc1_nlf_gain */
#define HILSIM_IPCORE_ADC1_NLF_ENABLE 0x1d4/**< adc1_nlf_enable */
#define HILSIM_IPCORE_ADC0_NLF_PRESC 0x1c0/**< adc0_nlf_presc */
#define HILSIM_IPCORE_ADC0_NLF_GAIN 0x1c4/**< adc0_nlf_gain */
#define HILSIM_IPCORE_ADC0_NLF_ENABLE 0x1c8/**< adc0_nlf_enable */
#define HILSIM_IPCORE_CFG_NLF_DONE 0x18/**< cfg_nlf_done */
#define HILSIM_IPCORE_NLF_SWITCH_SW_SWITCH 0x48/**< nlf_switch_sw_switch */
#define HILSIM_IPCORE_NLF_SWITCH_IO_MASK 0x44/**< nlf_switch_io_mask */
#define HILSIM_IPCORE_DAC1_CALIB_OFFSET 0x1c/**< dac1_calib_offset */
#define HILSIM_IPCORE_DAC1_CALIB_FACTOR 0x24/**< dac1_calib_factor */
#define HILSIM_IPCORE_DAC0_CALIB_OFFSET 0x18/**< dac0_calib_offset */
#define HILSIM_IPCORE_DAC0_CALIB_FACTOR 0x20/**< dac0_calib_factor */
#define HILSIM_IPCORE_ADC1_CALIB_OFFSET 0x4/**< adc1_calib_offset */
#define HILSIM_IPCORE_ADC1_CALIB_FACTOR 0xc/**< adc1_calib_factor */
#define HILSIM_IPCORE_ADC0_CALIB_OFFSET 0x0/**< adc0_calib_offset */
#define HILSIM_IPCORE_ADC0_CALIB_FACTOR 0x8/**< adc0_calib_factor */
#define HILSIM_IPCORE_ADC0_VALUE 0x10/**< adc0_value */
#define HILSIM_IPCORE_ADC1_VALUE 0x14/**< adc1_value */
#define HILSIM_IPCORE_NLF_SWITCH 0x40/**< nlf_switch */
