`timescale 1 ns / 10 ps
// Generated from Simulink block 
module thrtl_8ch_cfg_stub (
  input [32-1:0] data_in_a,
  input [32-1:0] data_in_b,
  input [32-1:0] data_in_c,
  input [32-1:0] data_in_d,
  input [32-1:0] data_in_e,
  input [32-1:0] data_in_f,
  input [32-1:0] data_in_g,
  input [32-1:0] data_in_h,
  input [1-1:0] m_axis_dma_tready,
  input [1-1:0] trigger_in_hw,
  input clk,
  input thrtl_8ch_cfg_aresetn,
  input [5-1:0] thrtl_8ch_cfg_cfg_in_s_axi_awaddr,
  input thrtl_8ch_cfg_cfg_in_s_axi_awvalid,
  input [32-1:0] thrtl_8ch_cfg_cfg_in_s_axi_wdata,
  input [4-1:0] thrtl_8ch_cfg_cfg_in_s_axi_wstrb,
  input thrtl_8ch_cfg_cfg_in_s_axi_wvalid,
  input thrtl_8ch_cfg_cfg_in_s_axi_bready,
  input [5-1:0] thrtl_8ch_cfg_cfg_in_s_axi_araddr,
  input thrtl_8ch_cfg_cfg_in_s_axi_arvalid,
  input thrtl_8ch_cfg_cfg_in_s_axi_rready,
  output [1-1:0] dma_ready_out,
  output [32-1:0] m_axis_dma_tdata,
  output [4-1:0] m_axis_dma_tkeep,
  output [1-1:0] m_axis_dma_tlast,
  output [1-1:0] m_axis_dma_tvalid,
  output thrtl_8ch_cfg_cfg_in_s_axi_awready,
  output thrtl_8ch_cfg_cfg_in_s_axi_wready,
  output [2-1:0] thrtl_8ch_cfg_cfg_in_s_axi_bresp,
  output thrtl_8ch_cfg_cfg_in_s_axi_bvalid,
  output thrtl_8ch_cfg_cfg_in_s_axi_arready,
  output [32-1:0] thrtl_8ch_cfg_cfg_in_s_axi_rdata,
  output [2-1:0] thrtl_8ch_cfg_cfg_in_s_axi_rresp,
  output thrtl_8ch_cfg_cfg_in_s_axi_rvalid
);
  Thrtl_8ch_cfg_0 sysgen_dut (
    .data_in_a(data_in_a),
    .data_in_b(data_in_b),
    .data_in_c(data_in_c),
    .data_in_d(data_in_d),
    .data_in_e(data_in_e),
    .data_in_f(data_in_f),
    .data_in_g(data_in_g),
    .data_in_h(data_in_h),
    .m_axis_dma_tready(m_axis_dma_tready),
    .trigger_in_hw(trigger_in_hw),
    .clk(clk),
    .thrtl_8ch_cfg_aresetn(thrtl_8ch_cfg_aresetn),
    .thrtl_8ch_cfg_cfg_in_s_axi_awaddr(thrtl_8ch_cfg_cfg_in_s_axi_awaddr),
    .thrtl_8ch_cfg_cfg_in_s_axi_awvalid(thrtl_8ch_cfg_cfg_in_s_axi_awvalid),
    .thrtl_8ch_cfg_cfg_in_s_axi_wdata(thrtl_8ch_cfg_cfg_in_s_axi_wdata),
    .thrtl_8ch_cfg_cfg_in_s_axi_wstrb(thrtl_8ch_cfg_cfg_in_s_axi_wstrb),
    .thrtl_8ch_cfg_cfg_in_s_axi_wvalid(thrtl_8ch_cfg_cfg_in_s_axi_wvalid),
    .thrtl_8ch_cfg_cfg_in_s_axi_bready(thrtl_8ch_cfg_cfg_in_s_axi_bready),
    .thrtl_8ch_cfg_cfg_in_s_axi_araddr(thrtl_8ch_cfg_cfg_in_s_axi_araddr),
    .thrtl_8ch_cfg_cfg_in_s_axi_arvalid(thrtl_8ch_cfg_cfg_in_s_axi_arvalid),
    .thrtl_8ch_cfg_cfg_in_s_axi_rready(thrtl_8ch_cfg_cfg_in_s_axi_rready),
    .dma_ready_out(dma_ready_out),
    .m_axis_dma_tdata(m_axis_dma_tdata),
    .m_axis_dma_tkeep(m_axis_dma_tkeep),
    .m_axis_dma_tlast(m_axis_dma_tlast),
    .m_axis_dma_tvalid(m_axis_dma_tvalid),
    .thrtl_8ch_cfg_cfg_in_s_axi_awready(thrtl_8ch_cfg_cfg_in_s_axi_awready),
    .thrtl_8ch_cfg_cfg_in_s_axi_wready(thrtl_8ch_cfg_cfg_in_s_axi_wready),
    .thrtl_8ch_cfg_cfg_in_s_axi_bresp(thrtl_8ch_cfg_cfg_in_s_axi_bresp),
    .thrtl_8ch_cfg_cfg_in_s_axi_bvalid(thrtl_8ch_cfg_cfg_in_s_axi_bvalid),
    .thrtl_8ch_cfg_cfg_in_s_axi_arready(thrtl_8ch_cfg_cfg_in_s_axi_arready),
    .thrtl_8ch_cfg_cfg_in_s_axi_rdata(thrtl_8ch_cfg_cfg_in_s_axi_rdata),
    .thrtl_8ch_cfg_cfg_in_s_axi_rresp(thrtl_8ch_cfg_cfg_in_s_axi_rresp),
    .thrtl_8ch_cfg_cfg_in_s_axi_rvalid(thrtl_8ch_cfg_cfg_in_s_axi_rvalid)
  );
endmodule
