`timescale 1ns / 1ps

// DMA Channel Mapper
// -> Maps LQG signals to DMA channels.

module dma_channel_mapper (
    input wire [13:0] lqg_uk_0,
    input wire [13:0] lqg_uk_1,
    input wire [13:0] lqg_yk_0,
    input wire [13:0] lqg_yk_1,
    input wire [24:0] lqg_xkhat_0,
    input wire [24:0] lqg_xkhat_1,
    input wire [24:0] lqg_xkhat_2,
    input wire [24:0] lqg_xkhat_3,
    input wire [24:0] lqg_xkhat_4,
    input wire [24:0] lqg_xkhat_5,
    input wire [24:0] lqg_xkhat_6,

    output wire [31:0] dma_channel_a,
    output wire [31:0] dma_channel_b,
    output wire [31:0] dma_channel_c,
    output wire [31:0] dma_channel_d,
    output wire [31:0] dma_channel_e,
    output wire [31:0] dma_channel_f,
    output wire [31:0] dma_channel_g,
    output wire [31:0] dma_channel_h
);

    assign dma_channel_a[0] = lqg_uk_0[0];
    assign dma_channel_a[1] = lqg_uk_0[1];
    assign dma_channel_a[2] = lqg_uk_0[2];
    assign dma_channel_a[3] = lqg_uk_0[3];
    assign dma_channel_a[4] = lqg_uk_0[4];
    assign dma_channel_a[5] = lqg_uk_0[5];
    assign dma_channel_a[6] = lqg_uk_0[6];
    assign dma_channel_a[7] = lqg_uk_0[7];
    assign dma_channel_a[8] = lqg_uk_0[8];
    assign dma_channel_a[9] = lqg_uk_0[9];
    assign dma_channel_a[10] = lqg_uk_0[10];
    assign dma_channel_a[11] = lqg_uk_0[11];
    assign dma_channel_a[12] = lqg_uk_0[12];
    assign dma_channel_a[13] = lqg_uk_0[13];
    assign dma_channel_a[14] = lqg_uk_1[0];
    assign dma_channel_a[15] = lqg_uk_1[1];
    assign dma_channel_a[16] = lqg_uk_1[2];
    assign dma_channel_a[17] = lqg_uk_1[3];
    assign dma_channel_a[18] = lqg_uk_1[4];
    assign dma_channel_a[19] = lqg_uk_1[5];
    assign dma_channel_a[20] = lqg_uk_1[6];
    assign dma_channel_a[21] = lqg_uk_1[7];
    assign dma_channel_a[22] = lqg_uk_1[8];
    assign dma_channel_a[23] = lqg_uk_1[9];
    assign dma_channel_a[24] = lqg_uk_1[10];
    assign dma_channel_a[25] = lqg_uk_1[11];
    assign dma_channel_a[26] = lqg_uk_1[12];
    assign dma_channel_a[27] = lqg_uk_1[13];
    assign dma_channel_a[28] = lqg_yk_0[0];
    assign dma_channel_a[29] = lqg_yk_0[1];
    assign dma_channel_a[30] = lqg_yk_0[2];
    assign dma_channel_a[31] = lqg_yk_0[3];
    assign dma_channel_b[0] = lqg_yk_0[4];
    assign dma_channel_b[1] = lqg_yk_0[5];
    assign dma_channel_b[2] = lqg_yk_0[6];
    assign dma_channel_b[3] = lqg_yk_0[7];
    assign dma_channel_b[4] = lqg_yk_0[8];
    assign dma_channel_b[5] = lqg_yk_0[9];
    assign dma_channel_b[6] = lqg_yk_0[10];
    assign dma_channel_b[7] = lqg_yk_0[11];
    assign dma_channel_b[8] = lqg_yk_0[12];
    assign dma_channel_b[9] = lqg_yk_0[13];
    assign dma_channel_b[10] = lqg_yk_1[0];
    assign dma_channel_b[11] = lqg_yk_1[1];
    assign dma_channel_b[12] = lqg_yk_1[2];
    assign dma_channel_b[13] = lqg_yk_1[3];
    assign dma_channel_b[14] = lqg_yk_1[4];
    assign dma_channel_b[15] = lqg_yk_1[5];
    assign dma_channel_b[16] = lqg_yk_1[6];
    assign dma_channel_b[17] = lqg_yk_1[7];
    assign dma_channel_b[18] = lqg_yk_1[8];
    assign dma_channel_b[19] = lqg_yk_1[9];
    assign dma_channel_b[20] = lqg_yk_1[10];
    assign dma_channel_b[21] = lqg_yk_1[11];
    assign dma_channel_b[22] = lqg_yk_1[12];
    assign dma_channel_b[23] = lqg_yk_1[13];
    assign dma_channel_b[24] = lqg_xkhat_0[0];
    assign dma_channel_b[25] = lqg_xkhat_0[1];
    assign dma_channel_b[26] = lqg_xkhat_0[2];
    assign dma_channel_b[27] = lqg_xkhat_0[3];
    assign dma_channel_b[28] = lqg_xkhat_0[4];
    assign dma_channel_b[29] = lqg_xkhat_0[5];
    assign dma_channel_b[30] = lqg_xkhat_0[6];
    assign dma_channel_b[31] = lqg_xkhat_0[7];
    assign dma_channel_c[0] = lqg_xkhat_0[8];
    assign dma_channel_c[1] = lqg_xkhat_0[9];
    assign dma_channel_c[2] = lqg_xkhat_0[10];
    assign dma_channel_c[3] = lqg_xkhat_0[11];
    assign dma_channel_c[4] = lqg_xkhat_0[12];
    assign dma_channel_c[5] = lqg_xkhat_0[13];
    assign dma_channel_c[6] = lqg_xkhat_0[14];
    assign dma_channel_c[7] = lqg_xkhat_0[15];
    assign dma_channel_c[8] = lqg_xkhat_0[16];
    assign dma_channel_c[9] = lqg_xkhat_0[17];
    assign dma_channel_c[10] = lqg_xkhat_0[18];
    assign dma_channel_c[11] = lqg_xkhat_0[19];
    assign dma_channel_c[12] = lqg_xkhat_0[20];
    assign dma_channel_c[13] = lqg_xkhat_0[21];
    assign dma_channel_c[14] = lqg_xkhat_0[22];
    assign dma_channel_c[15] = lqg_xkhat_0[23];
    assign dma_channel_c[16] = lqg_xkhat_0[24];
    assign dma_channel_c[17] = lqg_xkhat_1[0];
    assign dma_channel_c[18] = lqg_xkhat_1[1];
    assign dma_channel_c[19] = lqg_xkhat_1[2];
    assign dma_channel_c[20] = lqg_xkhat_1[3];
    assign dma_channel_c[21] = lqg_xkhat_1[4];
    assign dma_channel_c[22] = lqg_xkhat_1[5];
    assign dma_channel_c[23] = lqg_xkhat_1[6];
    assign dma_channel_c[24] = lqg_xkhat_1[7];
    assign dma_channel_c[25] = lqg_xkhat_1[8];
    assign dma_channel_c[26] = lqg_xkhat_1[9];
    assign dma_channel_c[27] = lqg_xkhat_1[10];
    assign dma_channel_c[28] = lqg_xkhat_1[11];
    assign dma_channel_c[29] = lqg_xkhat_1[12];
    assign dma_channel_c[30] = lqg_xkhat_1[13];
    assign dma_channel_c[31] = lqg_xkhat_1[14];
    assign dma_channel_d[0] = lqg_xkhat_1[15];
    assign dma_channel_d[1] = lqg_xkhat_1[16];
    assign dma_channel_d[2] = lqg_xkhat_1[17];
    assign dma_channel_d[3] = lqg_xkhat_1[18];
    assign dma_channel_d[4] = lqg_xkhat_1[19];
    assign dma_channel_d[5] = lqg_xkhat_1[20];
    assign dma_channel_d[6] = lqg_xkhat_1[21];
    assign dma_channel_d[7] = lqg_xkhat_1[22];
    assign dma_channel_d[8] = lqg_xkhat_1[23];
    assign dma_channel_d[9] = lqg_xkhat_1[24];
    assign dma_channel_d[10] = lqg_xkhat_2[0];
    assign dma_channel_d[11] = lqg_xkhat_2[1];
    assign dma_channel_d[12] = lqg_xkhat_2[2];
    assign dma_channel_d[13] = lqg_xkhat_2[3];
    assign dma_channel_d[14] = lqg_xkhat_2[4];
    assign dma_channel_d[15] = lqg_xkhat_2[5];
    assign dma_channel_d[16] = lqg_xkhat_2[6];
    assign dma_channel_d[17] = lqg_xkhat_2[7];
    assign dma_channel_d[18] = lqg_xkhat_2[8];
    assign dma_channel_d[19] = lqg_xkhat_2[9];
    assign dma_channel_d[20] = lqg_xkhat_2[10];
    assign dma_channel_d[21] = lqg_xkhat_2[11];
    assign dma_channel_d[22] = lqg_xkhat_2[12];
    assign dma_channel_d[23] = lqg_xkhat_2[13];
    assign dma_channel_d[24] = lqg_xkhat_2[14];
    assign dma_channel_d[25] = lqg_xkhat_2[15];
    assign dma_channel_d[26] = lqg_xkhat_2[16];
    assign dma_channel_d[27] = lqg_xkhat_2[17];
    assign dma_channel_d[28] = lqg_xkhat_2[18];
    assign dma_channel_d[29] = lqg_xkhat_2[19];
    assign dma_channel_d[30] = lqg_xkhat_2[20];
    assign dma_channel_d[31] = lqg_xkhat_2[21];
    assign dma_channel_e[0] = lqg_xkhat_2[22];
    assign dma_channel_e[1] = lqg_xkhat_2[23];
    assign dma_channel_e[2] = lqg_xkhat_2[24];
    assign dma_channel_e[3] = lqg_xkhat_3[0];
    assign dma_channel_e[4] = lqg_xkhat_3[1];
    assign dma_channel_e[5] = lqg_xkhat_3[2];
    assign dma_channel_e[6] = lqg_xkhat_3[3];
    assign dma_channel_e[7] = lqg_xkhat_3[4];
    assign dma_channel_e[8] = lqg_xkhat_3[5];
    assign dma_channel_e[9] = lqg_xkhat_3[6];
    assign dma_channel_e[10] = lqg_xkhat_3[7];
    assign dma_channel_e[11] = lqg_xkhat_3[8];
    assign dma_channel_e[12] = lqg_xkhat_3[9];
    assign dma_channel_e[13] = lqg_xkhat_3[10];
    assign dma_channel_e[14] = lqg_xkhat_3[11];
    assign dma_channel_e[15] = lqg_xkhat_3[12];
    assign dma_channel_e[16] = lqg_xkhat_3[13];
    assign dma_channel_e[17] = lqg_xkhat_3[14];
    assign dma_channel_e[18] = lqg_xkhat_3[15];
    assign dma_channel_e[19] = lqg_xkhat_3[16];
    assign dma_channel_e[20] = lqg_xkhat_3[17];
    assign dma_channel_e[21] = lqg_xkhat_3[18];
    assign dma_channel_e[22] = lqg_xkhat_3[19];
    assign dma_channel_e[23] = lqg_xkhat_3[20];
    assign dma_channel_e[24] = lqg_xkhat_3[21];
    assign dma_channel_e[25] = lqg_xkhat_3[22];
    assign dma_channel_e[26] = lqg_xkhat_3[23];
    assign dma_channel_e[27] = lqg_xkhat_3[24];
    assign dma_channel_e[28] = lqg_xkhat_4[0];
    assign dma_channel_e[29] = lqg_xkhat_4[1];
    assign dma_channel_e[30] = lqg_xkhat_4[2];
    assign dma_channel_e[31] = lqg_xkhat_4[3];
    assign dma_channel_f[0] = lqg_xkhat_4[4];
    assign dma_channel_f[1] = lqg_xkhat_4[5];
    assign dma_channel_f[2] = lqg_xkhat_4[6];
    assign dma_channel_f[3] = lqg_xkhat_4[7];
    assign dma_channel_f[4] = lqg_xkhat_4[8];
    assign dma_channel_f[5] = lqg_xkhat_4[9];
    assign dma_channel_f[6] = lqg_xkhat_4[10];
    assign dma_channel_f[7] = lqg_xkhat_4[11];
    assign dma_channel_f[8] = lqg_xkhat_4[12];
    assign dma_channel_f[9] = lqg_xkhat_4[13];
    assign dma_channel_f[10] = lqg_xkhat_4[14];
    assign dma_channel_f[11] = lqg_xkhat_4[15];
    assign dma_channel_f[12] = lqg_xkhat_4[16];
    assign dma_channel_f[13] = lqg_xkhat_4[17];
    assign dma_channel_f[14] = lqg_xkhat_4[18];
    assign dma_channel_f[15] = lqg_xkhat_4[19];
    assign dma_channel_f[16] = lqg_xkhat_4[20];
    assign dma_channel_f[17] = lqg_xkhat_4[21];
    assign dma_channel_f[18] = lqg_xkhat_4[22];
    assign dma_channel_f[19] = lqg_xkhat_4[23];
    assign dma_channel_f[20] = lqg_xkhat_4[24];
    assign dma_channel_f[21] = lqg_xkhat_5[0];
    assign dma_channel_f[22] = lqg_xkhat_5[1];
    assign dma_channel_f[23] = lqg_xkhat_5[2];
    assign dma_channel_f[24] = lqg_xkhat_5[3];
    assign dma_channel_f[25] = lqg_xkhat_5[4];
    assign dma_channel_f[26] = lqg_xkhat_5[5];
    assign dma_channel_f[27] = lqg_xkhat_5[6];
    assign dma_channel_f[28] = lqg_xkhat_5[7];
    assign dma_channel_f[29] = lqg_xkhat_5[8];
    assign dma_channel_f[30] = lqg_xkhat_5[9];
    assign dma_channel_f[31] = lqg_xkhat_5[10];
    assign dma_channel_g[0] = lqg_xkhat_5[11];
    assign dma_channel_g[1] = lqg_xkhat_5[12];
    assign dma_channel_g[2] = lqg_xkhat_5[13];
    assign dma_channel_g[3] = lqg_xkhat_5[14];
    assign dma_channel_g[4] = lqg_xkhat_5[15];
    assign dma_channel_g[5] = lqg_xkhat_5[16];
    assign dma_channel_g[6] = lqg_xkhat_5[17];
    assign dma_channel_g[7] = lqg_xkhat_5[18];
    assign dma_channel_g[8] = lqg_xkhat_5[19];
    assign dma_channel_g[9] = lqg_xkhat_5[20];
    assign dma_channel_g[10] = lqg_xkhat_5[21];
    assign dma_channel_g[11] = lqg_xkhat_5[22];
    assign dma_channel_g[12] = lqg_xkhat_5[23];
    assign dma_channel_g[13] = lqg_xkhat_5[24];
    assign dma_channel_g[14] = lqg_xkhat_6[0];
    assign dma_channel_g[15] = lqg_xkhat_6[1];
    assign dma_channel_g[16] = lqg_xkhat_6[2];
    assign dma_channel_g[17] = lqg_xkhat_6[3];
    assign dma_channel_g[18] = lqg_xkhat_6[4];
    assign dma_channel_g[19] = lqg_xkhat_6[5];
    assign dma_channel_g[20] = lqg_xkhat_6[6];
    assign dma_channel_g[21] = lqg_xkhat_6[7];
    assign dma_channel_g[22] = lqg_xkhat_6[8];
    assign dma_channel_g[23] = lqg_xkhat_6[9];
    assign dma_channel_g[24] = lqg_xkhat_6[10];
    assign dma_channel_g[25] = lqg_xkhat_6[11];
    assign dma_channel_g[26] = lqg_xkhat_6[12];
    assign dma_channel_g[27] = lqg_xkhat_6[13];
    assign dma_channel_g[28] = lqg_xkhat_6[14];
    assign dma_channel_g[29] = lqg_xkhat_6[15];
    assign dma_channel_g[30] = lqg_xkhat_6[16];
    assign dma_channel_g[31] = lqg_xkhat_6[17];
    assign dma_channel_h[0] = lqg_xkhat_6[18];
    assign dma_channel_h[1] = lqg_xkhat_6[19];
    assign dma_channel_h[2] = lqg_xkhat_6[20];
    assign dma_channel_h[3] = lqg_xkhat_6[21];
    assign dma_channel_h[4] = lqg_xkhat_6[22];
    assign dma_channel_h[5] = lqg_xkhat_6[23];
    assign dma_channel_h[6] = lqg_xkhat_6[24];

endmodule