`timescale 1 ns / 10 ps
// Generated from Simulink block 
module fpga_lqg_axi_stub (
  input [8-1:0] lqg_led_in,
  input [18-1:0] lqg_f_res_gw_0,
  input [18-1:0] lqg_f_res_gw_1,
  input [18-1:0] lqg_f_res_gw_2,
  input [18-1:0] lqg_f_res_gw_3,
  input [18-1:0] lqg_f_res_gw_4,
  input [18-1:0] lqg_f_res_gw_5,
  input [18-1:0] lqg_f_res_gw_6,
  input [18-1:0] lqg_f_res_gw_7,
  input [18-1:0] lqg_f_res_gw_8,
  input [18-1:0] lqg_f_res_gw_9,
  input [18-1:0] lqg_f_res_gw_10,
  input [18-1:0] lqg_f_res_gw_11,
  input [18-1:0] lqg_f_res_gw_12,
  input [18-1:0] lqg_f_res_gw_13,
  input [18-1:0] lqg_f_res_gw_14,
  input [18-1:0] lqg_f_res_gw_15,
  input [18-1:0] lqg_f_res_gw_16,
  input [18-1:0] lqg_f_res_gw_17,
  input [18-1:0] lqg_f_res_gw_18,
  input [18-1:0] lqg_f_res_gw_19,
  input [18-1:0] lqg_f_res_gw_20,
  input [18-1:0] lqg_f_res_gw_21,
  input [18-1:0] lqg_f_res_gw_22,
  input [18-1:0] lqg_f_res_gw_23,
  input [18-1:0] lqg_f_res_gw_24,
  input [18-1:0] lqg_f_res_gw_25,
  input [18-1:0] lqg_f_res_gw_26,
  input [18-1:0] lqg_f_res_gw_27,
  input [18-1:0] lqg_f_res_gw_28,
  input [18-1:0] lqg_f_res_gw_29,
  input [18-1:0] lqg_f_res_gw_30,
  input [18-1:0] lqg_f_res_gw_31,
  input [18-1:0] lqg_f_res_gw_32,
  input [18-1:0] lqg_f_res_gw_33,
  input [18-1:0] lqg_f_res_gw_34,
  input [18-1:0] lqg_f_res_gw_35,
  input [18-1:0] lqg_f_res_gw_36,
  input [18-1:0] lqg_f_res_gw_37,
  input [18-1:0] lqg_f_res_gw_38,
  input [18-1:0] lqg_f_res_gw_39,
  input [18-1:0] lqg_f_res_gw_40,
  input [18-1:0] lqg_f_res_gw_41,
  input [18-1:0] lqg_f_res_gw_42,
  input [18-1:0] lqg_f_res_gw_43,
  input [18-1:0] lqg_f_res_gw_44,
  input [18-1:0] lqg_f_res_gw_45,
  input [18-1:0] lqg_f_res_gw_46,
  input [18-1:0] lqg_f_res_gw_47,
  input [18-1:0] lqg_f_res_gw_48,
  input [5-1:0] lqg_f_shift_gw_0,
  input [5-1:0] lqg_f_shift_gw_1,
  input [5-1:0] lqg_f_shift_gw_2,
  input [5-1:0] lqg_f_shift_gw_3,
  input [5-1:0] lqg_f_shift_gw_4,
  input [5-1:0] lqg_f_shift_gw_5,
  input [5-1:0] lqg_f_shift_gw_6,
  input [5-1:0] lqg_f_shift_gw_7,
  input [5-1:0] lqg_f_shift_gw_8,
  input [5-1:0] lqg_f_shift_gw_9,
  input [5-1:0] lqg_f_shift_gw_10,
  input [5-1:0] lqg_f_shift_gw_11,
  input [5-1:0] lqg_f_shift_gw_12,
  input [5-1:0] lqg_f_shift_gw_13,
  input [5-1:0] lqg_f_shift_gw_14,
  input [5-1:0] lqg_f_shift_gw_15,
  input [5-1:0] lqg_f_shift_gw_16,
  input [5-1:0] lqg_f_shift_gw_17,
  input [5-1:0] lqg_f_shift_gw_18,
  input [5-1:0] lqg_f_shift_gw_19,
  input [5-1:0] lqg_f_shift_gw_20,
  input [5-1:0] lqg_f_shift_gw_21,
  input [5-1:0] lqg_f_shift_gw_22,
  input [5-1:0] lqg_f_shift_gw_23,
  input [5-1:0] lqg_f_shift_gw_24,
  input [5-1:0] lqg_f_shift_gw_25,
  input [5-1:0] lqg_f_shift_gw_26,
  input [5-1:0] lqg_f_shift_gw_27,
  input [5-1:0] lqg_f_shift_gw_28,
  input [5-1:0] lqg_f_shift_gw_29,
  input [5-1:0] lqg_f_shift_gw_30,
  input [5-1:0] lqg_f_shift_gw_31,
  input [5-1:0] lqg_f_shift_gw_32,
  input [5-1:0] lqg_f_shift_gw_33,
  input [5-1:0] lqg_f_shift_gw_34,
  input [5-1:0] lqg_f_shift_gw_35,
  input [5-1:0] lqg_f_shift_gw_36,
  input [5-1:0] lqg_f_shift_gw_37,
  input [5-1:0] lqg_f_shift_gw_38,
  input [5-1:0] lqg_f_shift_gw_39,
  input [5-1:0] lqg_f_shift_gw_40,
  input [5-1:0] lqg_f_shift_gw_41,
  input [5-1:0] lqg_f_shift_gw_42,
  input [5-1:0] lqg_f_shift_gw_43,
  input [5-1:0] lqg_f_shift_gw_44,
  input [5-1:0] lqg_f_shift_gw_45,
  input [5-1:0] lqg_f_shift_gw_46,
  input [5-1:0] lqg_f_shift_gw_47,
  input [5-1:0] lqg_f_shift_gw_48,
  input [18-1:0] lqg_gamma_res_gw_0,
  input [18-1:0] lqg_gamma_res_gw_1,
  input [18-1:0] lqg_gamma_res_gw_2,
  input [18-1:0] lqg_gamma_res_gw_3,
  input [18-1:0] lqg_gamma_res_gw_4,
  input [18-1:0] lqg_gamma_res_gw_5,
  input [18-1:0] lqg_gamma_res_gw_6,
  input [18-1:0] lqg_gamma_res_gw_7,
  input [18-1:0] lqg_gamma_res_gw_8,
  input [18-1:0] lqg_gamma_res_gw_9,
  input [18-1:0] lqg_gamma_res_gw_10,
  input [18-1:0] lqg_gamma_res_gw_11,
  input [18-1:0] lqg_gamma_res_gw_12,
  input [18-1:0] lqg_gamma_res_gw_13,
  input [5-1:0] lqg_gamma_shift_gw_0,
  input [5-1:0] lqg_gamma_shift_gw_1,
  input [5-1:0] lqg_gamma_shift_gw_2,
  input [5-1:0] lqg_gamma_shift_gw_3,
  input [5-1:0] lqg_gamma_shift_gw_4,
  input [5-1:0] lqg_gamma_shift_gw_5,
  input [5-1:0] lqg_gamma_shift_gw_6,
  input [5-1:0] lqg_gamma_shift_gw_7,
  input [5-1:0] lqg_gamma_shift_gw_8,
  input [5-1:0] lqg_gamma_shift_gw_9,
  input [5-1:0] lqg_gamma_shift_gw_10,
  input [5-1:0] lqg_gamma_shift_gw_11,
  input [5-1:0] lqg_gamma_shift_gw_12,
  input [5-1:0] lqg_gamma_shift_gw_13,
  input [18-1:0] lqg_k_res_gw_0,
  input [18-1:0] lqg_k_res_gw_1,
  input [18-1:0] lqg_k_res_gw_2,
  input [18-1:0] lqg_k_res_gw_3,
  input [18-1:0] lqg_k_res_gw_4,
  input [18-1:0] lqg_k_res_gw_5,
  input [18-1:0] lqg_k_res_gw_6,
  input [18-1:0] lqg_k_res_gw_7,
  input [18-1:0] lqg_k_res_gw_8,
  input [18-1:0] lqg_k_res_gw_9,
  input [18-1:0] lqg_k_res_gw_10,
  input [18-1:0] lqg_k_res_gw_11,
  input [18-1:0] lqg_k_res_gw_12,
  input [18-1:0] lqg_k_res_gw_13,
  input [6-1:0] lqg_k_shift_gw_0,
  input [6-1:0] lqg_k_shift_gw_1,
  input [6-1:0] lqg_k_shift_gw_2,
  input [6-1:0] lqg_k_shift_gw_3,
  input [6-1:0] lqg_k_shift_gw_4,
  input [6-1:0] lqg_k_shift_gw_5,
  input [6-1:0] lqg_k_shift_gw_6,
  input [6-1:0] lqg_k_shift_gw_7,
  input [6-1:0] lqg_k_shift_gw_8,
  input [6-1:0] lqg_k_shift_gw_9,
  input [6-1:0] lqg_k_shift_gw_10,
  input [6-1:0] lqg_k_shift_gw_11,
  input [6-1:0] lqg_k_shift_gw_12,
  input [6-1:0] lqg_k_shift_gw_13,
  input [18-1:0] lqg_l_res_gw_0,
  input [18-1:0] lqg_l_res_gw_1,
  input [18-1:0] lqg_l_res_gw_2,
  input [18-1:0] lqg_l_res_gw_3,
  input [18-1:0] lqg_l_res_gw_4,
  input [18-1:0] lqg_l_res_gw_5,
  input [18-1:0] lqg_l_res_gw_6,
  input [18-1:0] lqg_l_res_gw_7,
  input [18-1:0] lqg_l_res_gw_8,
  input [18-1:0] lqg_l_res_gw_9,
  input [18-1:0] lqg_l_res_gw_10,
  input [18-1:0] lqg_l_res_gw_11,
  input [18-1:0] lqg_l_res_gw_12,
  input [18-1:0] lqg_l_res_gw_13,
  input [5-1:0] lqg_l_shift_gw_0,
  input [5-1:0] lqg_l_shift_gw_1,
  input [5-1:0] lqg_l_shift_gw_2,
  input [5-1:0] lqg_l_shift_gw_3,
  input [5-1:0] lqg_l_shift_gw_4,
  input [5-1:0] lqg_l_shift_gw_5,
  input [5-1:0] lqg_l_shift_gw_6,
  input [5-1:0] lqg_l_shift_gw_7,
  input [5-1:0] lqg_l_shift_gw_8,
  input [5-1:0] lqg_l_shift_gw_9,
  input [5-1:0] lqg_l_shift_gw_10,
  input [5-1:0] lqg_l_shift_gw_11,
  input [5-1:0] lqg_l_shift_gw_12,
  input [5-1:0] lqg_l_shift_gw_13,
  input [18-1:0] uk_factor_gw_0,
  input [18-1:0] uk_factor_gw_1,
  input [14-1:0] uk_offset_gw_0,
  input [14-1:0] uk_offset_gw_1,
  input [18-1:0] yk_factor_gw_0,
  input [18-1:0] yk_factor_gw_1,
  input [14-1:0] yk_gw_0,
  input [14-1:0] yk_gw_1,
  input [14-1:0] yk_offset_gw_0,
  input [14-1:0] yk_offset_gw_1,
  input proc_sys_clk,
  input axi_sys_clk,
  input axi_sys_aresetn,
  input [4-1:0] axi_sys_s_axi_awaddr,
  input axi_sys_s_axi_awvalid,
  input [32-1:0] axi_sys_s_axi_wdata,
  input [4-1:0] axi_sys_s_axi_wstrb,
  input axi_sys_s_axi_wvalid,
  input axi_sys_s_axi_bready,
  input [4-1:0] axi_sys_s_axi_araddr,
  input axi_sys_s_axi_arvalid,
  input axi_sys_s_axi_rready,
  output [8-1:0] lqg_led_out,
  output [14-1:0] uk_gw_0,
  output [14-1:0] uk_gw_1,
  output [25-1:0] xkhat_gw_0,
  output [25-1:0] xkhat_gw_1,
  output [25-1:0] xkhat_gw_2,
  output [25-1:0] xkhat_gw_3,
  output [25-1:0] xkhat_gw_4,
  output [25-1:0] xkhat_gw_5,
  output [25-1:0] xkhat_gw_6,
  output axi_sys_s_axi_awready,
  output axi_sys_s_axi_wready,
  output [2-1:0] axi_sys_s_axi_bresp,
  output axi_sys_s_axi_bvalid,
  output axi_sys_s_axi_arready,
  output [32-1:0] axi_sys_s_axi_rdata,
  output [2-1:0] axi_sys_s_axi_rresp,
  output axi_sys_s_axi_rvalid
);
  fpga_lqg_axi sysgen_dut (
    .lqg_led_in(lqg_led_in),
    .lqg_f_res_gw_0(lqg_f_res_gw_0),
    .lqg_f_res_gw_1(lqg_f_res_gw_1),
    .lqg_f_res_gw_2(lqg_f_res_gw_2),
    .lqg_f_res_gw_3(lqg_f_res_gw_3),
    .lqg_f_res_gw_4(lqg_f_res_gw_4),
    .lqg_f_res_gw_5(lqg_f_res_gw_5),
    .lqg_f_res_gw_6(lqg_f_res_gw_6),
    .lqg_f_res_gw_7(lqg_f_res_gw_7),
    .lqg_f_res_gw_8(lqg_f_res_gw_8),
    .lqg_f_res_gw_9(lqg_f_res_gw_9),
    .lqg_f_res_gw_10(lqg_f_res_gw_10),
    .lqg_f_res_gw_11(lqg_f_res_gw_11),
    .lqg_f_res_gw_12(lqg_f_res_gw_12),
    .lqg_f_res_gw_13(lqg_f_res_gw_13),
    .lqg_f_res_gw_14(lqg_f_res_gw_14),
    .lqg_f_res_gw_15(lqg_f_res_gw_15),
    .lqg_f_res_gw_16(lqg_f_res_gw_16),
    .lqg_f_res_gw_17(lqg_f_res_gw_17),
    .lqg_f_res_gw_18(lqg_f_res_gw_18),
    .lqg_f_res_gw_19(lqg_f_res_gw_19),
    .lqg_f_res_gw_20(lqg_f_res_gw_20),
    .lqg_f_res_gw_21(lqg_f_res_gw_21),
    .lqg_f_res_gw_22(lqg_f_res_gw_22),
    .lqg_f_res_gw_23(lqg_f_res_gw_23),
    .lqg_f_res_gw_24(lqg_f_res_gw_24),
    .lqg_f_res_gw_25(lqg_f_res_gw_25),
    .lqg_f_res_gw_26(lqg_f_res_gw_26),
    .lqg_f_res_gw_27(lqg_f_res_gw_27),
    .lqg_f_res_gw_28(lqg_f_res_gw_28),
    .lqg_f_res_gw_29(lqg_f_res_gw_29),
    .lqg_f_res_gw_30(lqg_f_res_gw_30),
    .lqg_f_res_gw_31(lqg_f_res_gw_31),
    .lqg_f_res_gw_32(lqg_f_res_gw_32),
    .lqg_f_res_gw_33(lqg_f_res_gw_33),
    .lqg_f_res_gw_34(lqg_f_res_gw_34),
    .lqg_f_res_gw_35(lqg_f_res_gw_35),
    .lqg_f_res_gw_36(lqg_f_res_gw_36),
    .lqg_f_res_gw_37(lqg_f_res_gw_37),
    .lqg_f_res_gw_38(lqg_f_res_gw_38),
    .lqg_f_res_gw_39(lqg_f_res_gw_39),
    .lqg_f_res_gw_40(lqg_f_res_gw_40),
    .lqg_f_res_gw_41(lqg_f_res_gw_41),
    .lqg_f_res_gw_42(lqg_f_res_gw_42),
    .lqg_f_res_gw_43(lqg_f_res_gw_43),
    .lqg_f_res_gw_44(lqg_f_res_gw_44),
    .lqg_f_res_gw_45(lqg_f_res_gw_45),
    .lqg_f_res_gw_46(lqg_f_res_gw_46),
    .lqg_f_res_gw_47(lqg_f_res_gw_47),
    .lqg_f_res_gw_48(lqg_f_res_gw_48),
    .lqg_f_shift_gw_0(lqg_f_shift_gw_0),
    .lqg_f_shift_gw_1(lqg_f_shift_gw_1),
    .lqg_f_shift_gw_2(lqg_f_shift_gw_2),
    .lqg_f_shift_gw_3(lqg_f_shift_gw_3),
    .lqg_f_shift_gw_4(lqg_f_shift_gw_4),
    .lqg_f_shift_gw_5(lqg_f_shift_gw_5),
    .lqg_f_shift_gw_6(lqg_f_shift_gw_6),
    .lqg_f_shift_gw_7(lqg_f_shift_gw_7),
    .lqg_f_shift_gw_8(lqg_f_shift_gw_8),
    .lqg_f_shift_gw_9(lqg_f_shift_gw_9),
    .lqg_f_shift_gw_10(lqg_f_shift_gw_10),
    .lqg_f_shift_gw_11(lqg_f_shift_gw_11),
    .lqg_f_shift_gw_12(lqg_f_shift_gw_12),
    .lqg_f_shift_gw_13(lqg_f_shift_gw_13),
    .lqg_f_shift_gw_14(lqg_f_shift_gw_14),
    .lqg_f_shift_gw_15(lqg_f_shift_gw_15),
    .lqg_f_shift_gw_16(lqg_f_shift_gw_16),
    .lqg_f_shift_gw_17(lqg_f_shift_gw_17),
    .lqg_f_shift_gw_18(lqg_f_shift_gw_18),
    .lqg_f_shift_gw_19(lqg_f_shift_gw_19),
    .lqg_f_shift_gw_20(lqg_f_shift_gw_20),
    .lqg_f_shift_gw_21(lqg_f_shift_gw_21),
    .lqg_f_shift_gw_22(lqg_f_shift_gw_22),
    .lqg_f_shift_gw_23(lqg_f_shift_gw_23),
    .lqg_f_shift_gw_24(lqg_f_shift_gw_24),
    .lqg_f_shift_gw_25(lqg_f_shift_gw_25),
    .lqg_f_shift_gw_26(lqg_f_shift_gw_26),
    .lqg_f_shift_gw_27(lqg_f_shift_gw_27),
    .lqg_f_shift_gw_28(lqg_f_shift_gw_28),
    .lqg_f_shift_gw_29(lqg_f_shift_gw_29),
    .lqg_f_shift_gw_30(lqg_f_shift_gw_30),
    .lqg_f_shift_gw_31(lqg_f_shift_gw_31),
    .lqg_f_shift_gw_32(lqg_f_shift_gw_32),
    .lqg_f_shift_gw_33(lqg_f_shift_gw_33),
    .lqg_f_shift_gw_34(lqg_f_shift_gw_34),
    .lqg_f_shift_gw_35(lqg_f_shift_gw_35),
    .lqg_f_shift_gw_36(lqg_f_shift_gw_36),
    .lqg_f_shift_gw_37(lqg_f_shift_gw_37),
    .lqg_f_shift_gw_38(lqg_f_shift_gw_38),
    .lqg_f_shift_gw_39(lqg_f_shift_gw_39),
    .lqg_f_shift_gw_40(lqg_f_shift_gw_40),
    .lqg_f_shift_gw_41(lqg_f_shift_gw_41),
    .lqg_f_shift_gw_42(lqg_f_shift_gw_42),
    .lqg_f_shift_gw_43(lqg_f_shift_gw_43),
    .lqg_f_shift_gw_44(lqg_f_shift_gw_44),
    .lqg_f_shift_gw_45(lqg_f_shift_gw_45),
    .lqg_f_shift_gw_46(lqg_f_shift_gw_46),
    .lqg_f_shift_gw_47(lqg_f_shift_gw_47),
    .lqg_f_shift_gw_48(lqg_f_shift_gw_48),
    .lqg_gamma_res_gw_0(lqg_gamma_res_gw_0),
    .lqg_gamma_res_gw_1(lqg_gamma_res_gw_1),
    .lqg_gamma_res_gw_2(lqg_gamma_res_gw_2),
    .lqg_gamma_res_gw_3(lqg_gamma_res_gw_3),
    .lqg_gamma_res_gw_4(lqg_gamma_res_gw_4),
    .lqg_gamma_res_gw_5(lqg_gamma_res_gw_5),
    .lqg_gamma_res_gw_6(lqg_gamma_res_gw_6),
    .lqg_gamma_res_gw_7(lqg_gamma_res_gw_7),
    .lqg_gamma_res_gw_8(lqg_gamma_res_gw_8),
    .lqg_gamma_res_gw_9(lqg_gamma_res_gw_9),
    .lqg_gamma_res_gw_10(lqg_gamma_res_gw_10),
    .lqg_gamma_res_gw_11(lqg_gamma_res_gw_11),
    .lqg_gamma_res_gw_12(lqg_gamma_res_gw_12),
    .lqg_gamma_res_gw_13(lqg_gamma_res_gw_13),
    .lqg_gamma_shift_gw_0(lqg_gamma_shift_gw_0),
    .lqg_gamma_shift_gw_1(lqg_gamma_shift_gw_1),
    .lqg_gamma_shift_gw_2(lqg_gamma_shift_gw_2),
    .lqg_gamma_shift_gw_3(lqg_gamma_shift_gw_3),
    .lqg_gamma_shift_gw_4(lqg_gamma_shift_gw_4),
    .lqg_gamma_shift_gw_5(lqg_gamma_shift_gw_5),
    .lqg_gamma_shift_gw_6(lqg_gamma_shift_gw_6),
    .lqg_gamma_shift_gw_7(lqg_gamma_shift_gw_7),
    .lqg_gamma_shift_gw_8(lqg_gamma_shift_gw_8),
    .lqg_gamma_shift_gw_9(lqg_gamma_shift_gw_9),
    .lqg_gamma_shift_gw_10(lqg_gamma_shift_gw_10),
    .lqg_gamma_shift_gw_11(lqg_gamma_shift_gw_11),
    .lqg_gamma_shift_gw_12(lqg_gamma_shift_gw_12),
    .lqg_gamma_shift_gw_13(lqg_gamma_shift_gw_13),
    .lqg_k_res_gw_0(lqg_k_res_gw_0),
    .lqg_k_res_gw_1(lqg_k_res_gw_1),
    .lqg_k_res_gw_2(lqg_k_res_gw_2),
    .lqg_k_res_gw_3(lqg_k_res_gw_3),
    .lqg_k_res_gw_4(lqg_k_res_gw_4),
    .lqg_k_res_gw_5(lqg_k_res_gw_5),
    .lqg_k_res_gw_6(lqg_k_res_gw_6),
    .lqg_k_res_gw_7(lqg_k_res_gw_7),
    .lqg_k_res_gw_8(lqg_k_res_gw_8),
    .lqg_k_res_gw_9(lqg_k_res_gw_9),
    .lqg_k_res_gw_10(lqg_k_res_gw_10),
    .lqg_k_res_gw_11(lqg_k_res_gw_11),
    .lqg_k_res_gw_12(lqg_k_res_gw_12),
    .lqg_k_res_gw_13(lqg_k_res_gw_13),
    .lqg_k_shift_gw_0(lqg_k_shift_gw_0),
    .lqg_k_shift_gw_1(lqg_k_shift_gw_1),
    .lqg_k_shift_gw_2(lqg_k_shift_gw_2),
    .lqg_k_shift_gw_3(lqg_k_shift_gw_3),
    .lqg_k_shift_gw_4(lqg_k_shift_gw_4),
    .lqg_k_shift_gw_5(lqg_k_shift_gw_5),
    .lqg_k_shift_gw_6(lqg_k_shift_gw_6),
    .lqg_k_shift_gw_7(lqg_k_shift_gw_7),
    .lqg_k_shift_gw_8(lqg_k_shift_gw_8),
    .lqg_k_shift_gw_9(lqg_k_shift_gw_9),
    .lqg_k_shift_gw_10(lqg_k_shift_gw_10),
    .lqg_k_shift_gw_11(lqg_k_shift_gw_11),
    .lqg_k_shift_gw_12(lqg_k_shift_gw_12),
    .lqg_k_shift_gw_13(lqg_k_shift_gw_13),
    .lqg_l_res_gw_0(lqg_l_res_gw_0),
    .lqg_l_res_gw_1(lqg_l_res_gw_1),
    .lqg_l_res_gw_2(lqg_l_res_gw_2),
    .lqg_l_res_gw_3(lqg_l_res_gw_3),
    .lqg_l_res_gw_4(lqg_l_res_gw_4),
    .lqg_l_res_gw_5(lqg_l_res_gw_5),
    .lqg_l_res_gw_6(lqg_l_res_gw_6),
    .lqg_l_res_gw_7(lqg_l_res_gw_7),
    .lqg_l_res_gw_8(lqg_l_res_gw_8),
    .lqg_l_res_gw_9(lqg_l_res_gw_9),
    .lqg_l_res_gw_10(lqg_l_res_gw_10),
    .lqg_l_res_gw_11(lqg_l_res_gw_11),
    .lqg_l_res_gw_12(lqg_l_res_gw_12),
    .lqg_l_res_gw_13(lqg_l_res_gw_13),
    .lqg_l_shift_gw_0(lqg_l_shift_gw_0),
    .lqg_l_shift_gw_1(lqg_l_shift_gw_1),
    .lqg_l_shift_gw_2(lqg_l_shift_gw_2),
    .lqg_l_shift_gw_3(lqg_l_shift_gw_3),
    .lqg_l_shift_gw_4(lqg_l_shift_gw_4),
    .lqg_l_shift_gw_5(lqg_l_shift_gw_5),
    .lqg_l_shift_gw_6(lqg_l_shift_gw_6),
    .lqg_l_shift_gw_7(lqg_l_shift_gw_7),
    .lqg_l_shift_gw_8(lqg_l_shift_gw_8),
    .lqg_l_shift_gw_9(lqg_l_shift_gw_9),
    .lqg_l_shift_gw_10(lqg_l_shift_gw_10),
    .lqg_l_shift_gw_11(lqg_l_shift_gw_11),
    .lqg_l_shift_gw_12(lqg_l_shift_gw_12),
    .lqg_l_shift_gw_13(lqg_l_shift_gw_13),
    .uk_factor_gw_0(uk_factor_gw_0),
    .uk_factor_gw_1(uk_factor_gw_1),
    .uk_offset_gw_0(uk_offset_gw_0),
    .uk_offset_gw_1(uk_offset_gw_1),
    .yk_factor_gw_0(yk_factor_gw_0),
    .yk_factor_gw_1(yk_factor_gw_1),
    .yk_gw_0(yk_gw_0),
    .yk_gw_1(yk_gw_1),
    .yk_offset_gw_0(yk_offset_gw_0),
    .yk_offset_gw_1(yk_offset_gw_1),
    .proc_sys_clk(proc_sys_clk),
    .axi_sys_clk(axi_sys_clk),
    .axi_sys_aresetn(axi_sys_aresetn),
    .axi_sys_s_axi_awaddr(axi_sys_s_axi_awaddr),
    .axi_sys_s_axi_awvalid(axi_sys_s_axi_awvalid),
    .axi_sys_s_axi_wdata(axi_sys_s_axi_wdata),
    .axi_sys_s_axi_wstrb(axi_sys_s_axi_wstrb),
    .axi_sys_s_axi_wvalid(axi_sys_s_axi_wvalid),
    .axi_sys_s_axi_bready(axi_sys_s_axi_bready),
    .axi_sys_s_axi_araddr(axi_sys_s_axi_araddr),
    .axi_sys_s_axi_arvalid(axi_sys_s_axi_arvalid),
    .axi_sys_s_axi_rready(axi_sys_s_axi_rready),
    .lqg_led_out(lqg_led_out),
    .uk_gw_0(uk_gw_0),
    .uk_gw_1(uk_gw_1),
    .xkhat_gw_0(xkhat_gw_0),
    .xkhat_gw_1(xkhat_gw_1),
    .xkhat_gw_2(xkhat_gw_2),
    .xkhat_gw_3(xkhat_gw_3),
    .xkhat_gw_4(xkhat_gw_4),
    .xkhat_gw_5(xkhat_gw_5),
    .xkhat_gw_6(xkhat_gw_6),
    .axi_sys_s_axi_awready(axi_sys_s_axi_awready),
    .axi_sys_s_axi_wready(axi_sys_s_axi_wready),
    .axi_sys_s_axi_bresp(axi_sys_s_axi_bresp),
    .axi_sys_s_axi_bvalid(axi_sys_s_axi_bvalid),
    .axi_sys_s_axi_arready(axi_sys_s_axi_arready),
    .axi_sys_s_axi_rdata(axi_sys_s_axi_rdata),
    .axi_sys_s_axi_rresp(axi_sys_s_axi_rresp),
    .axi_sys_s_axi_rvalid(axi_sys_s_axi_rvalid)
  );
endmodule
