// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
// Date        : Mon May  4 12:20:02 2026
// Host        : tp-p14s running 64-bit Ubuntu 24.04.3 LTS
// Command     : write_verilog -force -mode synth_stub
//               /home/user/work/acin/projects/redpitaya-hil-simulator/ipcore/bds/design_0_rpgen2/ip/design_0_hilsim_ipcore_0_0/design_0_hilsim_ipcore_0_0_stub.v
// Design      : design_0_hilsim_ipcore_0_0
// Purpose     : Stub declaration of top-level module interface
// Device      : xc7z020clg400-1
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
(* CHECK_LICENSE_TYPE = "design_0_hilsim_ipcore_0_0,hilsim_ipcore,{}" *) (* DowngradeIPIdentifiedWarnings = "yes" *) (* IP_DEFINITION_SOURCE = "sysgen" *) 
(* X_CORE_INFO = "hilsim_ipcore,Vivado 2024.2" *) 
module design_0_hilsim_ipcore_0_0(adc_ch0_in, adc_ch1_in, 
  procclk_nlf_sw_ext_in, axi_domain_clk, proc_domain_clk, adc_dac_domain_clk, 
  axi_domain_aresetn, axi_domain_s_axi_awaddr, axi_domain_s_axi_awvalid, 
  axi_domain_s_axi_wdata, axi_domain_s_axi_wstrb, axi_domain_s_axi_wvalid, 
  axi_domain_s_axi_bready, axi_domain_s_axi_araddr, axi_domain_s_axi_arvalid, 
  axi_domain_s_axi_rready, axi_domain_axi_b_s_axi_awaddr, 
  axi_domain_axi_b_s_axi_awvalid, axi_domain_axi_b_s_axi_wdata, 
  axi_domain_axi_b_s_axi_wstrb, axi_domain_axi_b_s_axi_wvalid, 
  axi_domain_axi_b_s_axi_bready, axi_domain_axi_b_s_axi_araddr, 
  axi_domain_axi_b_s_axi_arvalid, axi_domain_axi_b_s_axi_rready, dac_ch0_out, 
  dac_ch1_out, dma_ch1_out, dma_ch2h_out, dma_ch2l_out, dma_trigger_out, leds_out, 
  axi_domain_s_axi_awready, axi_domain_s_axi_wready, axi_domain_s_axi_bresp, 
  axi_domain_s_axi_bvalid, axi_domain_s_axi_arready, axi_domain_s_axi_rdata, 
  axi_domain_s_axi_rresp, axi_domain_s_axi_rvalid, axi_domain_axi_b_s_axi_awready, 
  axi_domain_axi_b_s_axi_wready, axi_domain_axi_b_s_axi_bresp, 
  axi_domain_axi_b_s_axi_bvalid, axi_domain_axi_b_s_axi_arready, 
  axi_domain_axi_b_s_axi_rdata, axi_domain_axi_b_s_axi_rresp, 
  axi_domain_axi_b_s_axi_rvalid)
/* synthesis syn_black_box black_box_pad_pin="adc_ch0_in[13:0],adc_ch1_in[13:0],procclk_nlf_sw_ext_in[8:0],axi_domain_aresetn,axi_domain_s_axi_awaddr[8:0],axi_domain_s_axi_awvalid,axi_domain_s_axi_wdata[31:0],axi_domain_s_axi_wstrb[3:0],axi_domain_s_axi_wvalid,axi_domain_s_axi_bready,axi_domain_s_axi_araddr[8:0],axi_domain_s_axi_arvalid,axi_domain_s_axi_rready,axi_domain_axi_b_s_axi_awaddr[6:0],axi_domain_axi_b_s_axi_awvalid,axi_domain_axi_b_s_axi_wdata[31:0],axi_domain_axi_b_s_axi_wstrb[3:0],axi_domain_axi_b_s_axi_wvalid,axi_domain_axi_b_s_axi_bready,axi_domain_axi_b_s_axi_araddr[6:0],axi_domain_axi_b_s_axi_arvalid,axi_domain_axi_b_s_axi_rready,dac_ch0_out[13:0],dac_ch1_out[13:0],dma_ch1_out[31:0],dma_ch2h_out[15:0],dma_ch2l_out[15:0],dma_trigger_out[0:0],leds_out[7:0],axi_domain_s_axi_awready,axi_domain_s_axi_wready,axi_domain_s_axi_bresp[1:0],axi_domain_s_axi_bvalid,axi_domain_s_axi_arready,axi_domain_s_axi_rdata[31:0],axi_domain_s_axi_rresp[1:0],axi_domain_s_axi_rvalid,axi_domain_axi_b_s_axi_awready,axi_domain_axi_b_s_axi_wready,axi_domain_axi_b_s_axi_bresp[1:0],axi_domain_axi_b_s_axi_bvalid,axi_domain_axi_b_s_axi_arready,axi_domain_axi_b_s_axi_rdata[31:0],axi_domain_axi_b_s_axi_rresp[1:0],axi_domain_axi_b_s_axi_rvalid" */
/* synthesis syn_force_seq_prim="axi_domain_clk" */
/* synthesis syn_force_seq_prim="proc_domain_clk" */
/* synthesis syn_force_seq_prim="adc_dac_domain_clk" */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 adc_ch0_in DATA" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME adc_ch0_in, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 14} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 12} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value true}}}}}}" *) input [13:0]adc_ch0_in;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 adc_ch1_in DATA" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME adc_ch1_in, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 14} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 12} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value true}}}}}}" *) input [13:0]adc_ch1_in;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 procclk_nlf_sw_ext_in DATA" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME procclk_nlf_sw_ext_in, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 9} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}}}}" *) input [8:0]procclk_nlf_sw_ext_in;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 axi_domain_clk CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME axi_domain_clk, ASSOCIATED_RESET axi_domain_aresetn, ASSOCIATED_BUSIF axi_domain_axi_b_s_axi:axi_domain_s_axi, FREQ_HZ 125000000, FREQ_TOLERANCE_HZ 0, PHASE 0.000, CLK_DOMAIN design_0_processing_system7_0_FCLK_CLK0, INSERT_VIP 0" *) input axi_domain_clk /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 proc_domain_clk CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME proc_domain_clk, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN /pll_procclk_clk_out1, INSERT_VIP 0" *) input proc_domain_clk /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 adc_dac_domain_clk CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME adc_dac_domain_clk, FREQ_HZ 125000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_0_axis_red_pitaya_adc_1_0_adc_clk, INSERT_VIP 0" *) input adc_dac_domain_clk /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 axi_domain_aresetn RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME axi_domain_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input axi_domain_aresetn;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi AWADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME axi_domain_s_axi, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 125000000, ID_WIDTH 0, ADDR_WIDTH 9, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.000, CLK_DOMAIN design_0_processing_system7_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [8:0]axi_domain_s_axi_awaddr;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi AWVALID" *) input axi_domain_s_axi_awvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi WDATA" *) input [31:0]axi_domain_s_axi_wdata;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi WSTRB" *) input [3:0]axi_domain_s_axi_wstrb;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi WVALID" *) input axi_domain_s_axi_wvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi BREADY" *) input axi_domain_s_axi_bready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi ARADDR" *) input [8:0]axi_domain_s_axi_araddr;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi ARVALID" *) input axi_domain_s_axi_arvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi RREADY" *) input axi_domain_s_axi_rready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi AWADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME axi_domain_axi_b_s_axi, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 125000000, ID_WIDTH 0, ADDR_WIDTH 7, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.000, CLK_DOMAIN design_0_processing_system7_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [6:0]axi_domain_axi_b_s_axi_awaddr;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi AWVALID" *) input axi_domain_axi_b_s_axi_awvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi WDATA" *) input [31:0]axi_domain_axi_b_s_axi_wdata;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi WSTRB" *) input [3:0]axi_domain_axi_b_s_axi_wstrb;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi WVALID" *) input axi_domain_axi_b_s_axi_wvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi BREADY" *) input axi_domain_axi_b_s_axi_bready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi ARADDR" *) input [6:0]axi_domain_axi_b_s_axi_araddr;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi ARVALID" *) input axi_domain_axi_b_s_axi_arvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi RREADY" *) input axi_domain_axi_b_s_axi_rready;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 dac_ch0_out DATA" *) (* X_INTERFACE_MODE = "master" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME dac_ch0_out, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 14} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 12} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value true}}}}}}" *) output [13:0]dac_ch0_out;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 dac_ch1_out DATA" *) (* X_INTERFACE_MODE = "master" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME dac_ch1_out, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 14} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 12} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value true}}}}}}" *) output [13:0]dac_ch1_out;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 dma_ch1_out DATA" *) (* X_INTERFACE_MODE = "master" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME dma_ch1_out, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 32} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}}}}" *) output [31:0]dma_ch1_out;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 dma_ch2h_out DATA" *) (* X_INTERFACE_MODE = "master" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME dma_ch2h_out, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 16} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}}}}" *) output [15:0]dma_ch2h_out;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 dma_ch2l_out DATA" *) (* X_INTERFACE_MODE = "master" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME dma_ch2l_out, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 16} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}}}}" *) output [15:0]dma_ch2l_out;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 dma_trigger_out DATA" *) (* X_INTERFACE_MODE = "master" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME dma_trigger_out, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}}}}" *) output [0:0]dma_trigger_out;
  (* X_INTERFACE_INFO = "xilinx.com:signal:data:1.0 leds_out DATA" *) (* X_INTERFACE_MODE = "master" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME leds_out, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {DATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} real {fixed {fractwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}}}}" *) output [7:0]leds_out;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi AWREADY" *) output axi_domain_s_axi_awready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi WREADY" *) output axi_domain_s_axi_wready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi BRESP" *) output [1:0]axi_domain_s_axi_bresp;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi BVALID" *) output axi_domain_s_axi_bvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi ARREADY" *) output axi_domain_s_axi_arready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi RDATA" *) output [31:0]axi_domain_s_axi_rdata;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi RRESP" *) output [1:0]axi_domain_s_axi_rresp;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_s_axi RVALID" *) output axi_domain_s_axi_rvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi AWREADY" *) output axi_domain_axi_b_s_axi_awready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi WREADY" *) output axi_domain_axi_b_s_axi_wready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi BRESP" *) output [1:0]axi_domain_axi_b_s_axi_bresp;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi BVALID" *) output axi_domain_axi_b_s_axi_bvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi ARREADY" *) output axi_domain_axi_b_s_axi_arready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi RDATA" *) output [31:0]axi_domain_axi_b_s_axi_rdata;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi RRESP" *) output [1:0]axi_domain_axi_b_s_axi_rresp;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 axi_domain_axi_b_s_axi RVALID" *) output axi_domain_axi_b_s_axi_rvalid;
endmodule
